# Generated by Django 4.0.4 on 2022-06-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('berita_id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=128)),
                ('tanggal', models.DateField(auto_now=True)),
                ('deskripsi', models.TextField()),
                ('url', models.URLField()),
                ('thumbnail', models.URLField(verbose_name='Url thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Kencan',
            fields=[
                ('kencan_id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('tempat', models.TextField()),
                ('pasangan_id', models.IntegerField(db_column='pasangan_id', null=True)),
                ('pasangan', models.CharField(max_length=32)),
                ('biaya', models.IntegerField()),
                ('status_kencan_id', models.IntegerField(db_column='status_kencan_id', null=True)),
                ('status_kencan', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('laporan_id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=128)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasangan',
            fields=[
                ('pasangan_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('special_name', models.CharField(max_length=32)),
                ('avatar', models.URLField()),
                ('ulang_tahun', models.DateField(null=True)),
                ('tanggal_jadian', models.DateField(null=True)),
                ('kencan_terakhir', models.DateField(null=True)),
                ('status_pasangan_id', models.IntegerField(db_column='status_pasangan_id', null=True)),
                ('status_pasangan', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StatusKencan',
            fields=[
                ('status_kencan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('keterangan', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPasangan',
            fields=[
                ('status_pasangan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('keterangan', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('avatar', models.URLField(default='https://www.petwellnessaz.com/wp-content/uploads/2020/07/blank-profile-picture-973460_640-300x300-1-300x300.png')),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
