# Generated by Django 4.0.4 on 2022-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuskencan',
            name='status_kencan_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statuspasangan',
            name='status_pasangan_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
