# Generated by Django 4.0.4 on 2022-04-25 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_alter_statuskencan_status_kencan_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('laporan_id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=128)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='berita',
            name='tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
